// Code generated by MockGen. DO NOT EDIT.
// Source: services.go
//
// Generated by this command:
//
//	mockgen -source=services.go -destination=mocks/mock.go
//

// Package mock_services is a generated GoMock package.
package mock_services

import (
	models "gin/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRoom is a mock of Room interface.
type MockRoom struct {
	ctrl     *gomock.Controller
	recorder *MockRoomMockRecorder
	isgomock struct{}
}

// MockRoomMockRecorder is the mock recorder for MockRoom.
type MockRoomMockRecorder struct {
	mock *MockRoom
}

// NewMockRoom creates a new mock instance.
func NewMockRoom(ctrl *gomock.Controller) *MockRoom {
	mock := &MockRoom{ctrl: ctrl}
	mock.recorder = &MockRoomMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoom) EXPECT() *MockRoomMockRecorder {
	return m.recorder
}

// CreateRoom mocks base method.
func (m *MockRoom) CreateRoom(room models.RoomCreate) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", room)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockRoomMockRecorder) CreateRoom(room any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockRoom)(nil).CreateRoom), room)
}

// GetRoomById mocks base method.
func (m *MockRoom) GetRoomById(id int) (*models.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomById", id)
	ret0, _ := ret[0].(*models.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomById indicates an expected call of GetRoomById.
func (mr *MockRoomMockRecorder) GetRoomById(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomById", reflect.TypeOf((*MockRoom)(nil).GetRoomById), id)
}
